format_strings = false
reorder_imports = true
hard_tabs = false
imports_granularity='Crate'
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
wrap_comments = true
edition = "2021"