[env]
ENV_DIR = {source="${CARGO_MAKE_PROFILE}", default_value = "debug", mapping = {release = "release"}}
CARGO_TARGET_DIR = {value = "target", condition = {env_not_set = ["CARGO_TARGET_DIR"]}}
CARGO_MANIFEST_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"

[env.release]
CARGO_RELEASE_ARGS = "--release"

[tasks.udp-build-local]
args = ["build", "--features", "use-udp", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.webrtc-build-local]
args = ["build", "--features", "use-webrtc", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.udp-run-local]
command = "${CARGO_TARGET_DIR}/${ENV_DIR}/${CARGO_MAKE_BINARY_EXECUTABLE_NAME}"
dependencies = ["udp-build-local"]

[tasks.webrtc-run-local]
command = "${CARGO_TARGET_DIR}/${ENV_DIR}/${CARGO_MAKE_BINARY_EXECUTABLE_NAME}"
dependencies = ["webrtc-build-local"]